all:
	javac -cp algs4.jar Percolation.java PercolationStats.java PercolationVisualizer.java

run:
	#java -cp ".:algs4.jar" PercolationStats 200 100
	java -cp ".:algs4.jar" PercolationVisualizer input7.txt

clean:
	rm -f *.class
